# CSV Processing Pipeline Template
# Processes CSV files from input directory to output directory

pipeline:
  name: "CSV Data Processor"
  description: "Processes CSV files with validation and transformation"
  
  input:
    type: "file"
    path: "/opt/nifi/input"
    format: "csv"
    polling_interval: "10s"
    
  processing:
    - validate:
        enabled: true
        rules:
          - column: "email"
            type: "email"
          - column: "phone"
            type: "phone"
    
    - transform:
        enabled: true
        operations:
          - uppercase: ["name", "company"]
          - lowercase: ["email"]
          - trim: ["all"]
    
  output:
    type: "file"
    path: "/opt/nifi/output"
    format: "json"
    filename_pattern: "processed_${timestamp}.json"
    
  error_handling:
    path: "/opt/nifi/errors"
    format: "csv"
    include_original: true
    
  monitoring:
    alerts:
      - type: "error_rate"
        threshold: "5%"
      - type: "throughput"
        min_records_per_minute: 10