# kind cluster configuration for WSL InfoMetis deployment
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: infometis

# Configure nodes
nodes:
- role: control-plane
  # Enable ingress controller support
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # Port mappings for Traefik ingress
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  # Additional port for NiFi UI (optional direct access)
  - containerPort: 8080
    hostPort: 9090
    protocol: TCP

# Configure networking for WSL
networking:
  # Avoid conflicts with WSL networking
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # Disable default CNI to allow manual setup if needed
  disableDefaultCNI: false
  # Use IPv4 only for WSL compatibility
  ipFamily: ipv4